### PR TITLE
feat: add mermaid language configuration

### PR DESCRIPTION
**Pull request by CatBraaain**
Add language configuration and support features bellow
- Comment toggling
- Brackets definition
- Autoclosing
- Autosurrounding
- Folding
- Indentation Rules

Code snippets
https://code.visualstudio.com/api/language-extensions/language-configuration-guide

Test
test

I'm very new to pull request, I welcome any feedback.

### CODE REVIEW

**Comment by CatBraaain** [comment]
and support embed mermaid in markdown
test gif

**Comment by bpruitt-goddard** [comment]
I like the comment toggling and the embedded mermaid in markdown support, but I worry that the bracket matching/autoclosing will give issues. Consider the relationship syntax in ER diagrams. This change will make it less clear that they are valid. For example I'm seeing these brace closing errors in the [ER test file](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/blob/master/tests/diagrams/er.test.mermaid?short_path=7c8463b):

image

A similar problem happens when trying to create new relationships - the bracket is attempted to autoclose ,which is not relevant for the relationship. Could we remove the brace functionality from here?

**Comment by CatBraaain** [comment]
Thanks for reviewing.
After receiving your feedback, I found some similar problems in curl bracket and square bracket.



I removed some features what I'm not sure it affects any problems.

## Current feature
- Comment toggling
  - in mermaid language
  - in embedded mermaid block in markdown language

**Comment by bpruitt-goddard** [comment]
The PR looks good, there are just some prettier issues in a file. Can you fix these before merge?
> Checking formatting...
> [warn] syntaxes/mermaid.tmLanguage-markdown.yaml
> [warn] Code style issues found in the above file. Run Prettier to fix.
> Problem running prettier with --check **/*.{js,yaml,md}

**Comment by CatBraaain** [comment]
Thanks for reviewing.
I ran `npx prettier --write syntaxes/mermaid.tmLanguage-markdown.yaml` and commit it again.

**Comment by CatBraaain** [comment]
Thanks to you, I'm glad I succeeded my first pull request.

**Comment by bpruitt-goddard** [comment]
Awesome job on your first PR! Thanks for picking this project to contribute to!

**Pull request merged**
